site_name: NALC Application Documentation
site_url: https://nalcorg.github.io
site_author: you
site_description: All documentation for NALC's applications
nav:
  - About: index.md
  - Correspondence: correspondence.md
  # - By-Laws: bylaws.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml